version: '3.9'
services:
  database:
    image: postgres:13
    container_name: database
    ports:
      - 5432:5432
    env_file:
      - ./postgres/postgres.env
    volumes:
      - pgdata:/var/lib/postgresql/data 
  
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    entrypoint: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - redisdata:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - 8080:80
    restart: unless-stopped
    env_file:
      - ./pgadmin/pgadmin.env
    volumes:
      - pgadmindata:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - ./pgadmin/pgpass:/pgpass

  redis-cmder:
    image: rediscommander/redis-commander:latest
    container_name: rediscmder
    hostname: rediscmder
    environment:
      - REDIS_HOSTS=docker:redis:6379:0:redisPassword
    ports:
      - 8082:8081

volumes:
  pgdata:
  redisdata:
  pgadmindata: